name: Linux-CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: Display structure of downloaded files
        run: ls -R
      - name: Configure and Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j2
      - name: Test
        run: |
          cd build
          make check
