name: Linux-CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure and Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j2
      - name: Test
        run: |
          cd build
          make check
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: bruh
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}
          # The desired behavior if no files are found using the provided path.
